## first stage
FROM golang:latest AS builder
COPY . /app
WORKDIR /app
RUN go mod download
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o smoothdb

## second stage
FROM alpine
COPY --from=builder /app /app
COPY --from=builder /app/misc/config.jsonc /app/config.jsonc
WORKDIR /app
EXPOSE 4000
CMD ./start.sh